language: python
python:
	- '2.6'
	- '2.7'
	- 'pypy'
	- '3.4'

install:
	- pip install -rtests/requirements.txt
	- pip install .

script: tox -eflake8 && python setup.py nosetests
after_success: coveralls
