#
# Run cocaine-flow-setup to configure this interactive
#

PORT: 5000
#SECRET_KEY: 
UPLOAD_FOLDER: /tmp
ALLOWED_EXTENSIONS: [.gz]

#STORAGE: elliptics
#STORAGE: mongo 

# IF STORAGE: elliptics THEN
#ELLIPTICS_GROUPS: [1, 2, 3]
#ELLIPTICS_NODES: {anyeeliptics1.host: 1025, anyelliptics2.host : 1025}
#MAX_CONTENT_LENGTH: 16777216

#IF STORAGE: mongo THEN
#MONGO_DBNAME: cocaine-flow
#MONGO_HOST: anymongodb.host
#MONGO_PORT: 27017
